### ISSUE TITLE
Can't get cert

### ISSUE THREAD

**Issue by JanJastrow** [desec-io/certbot-hook#9]
Hi, I've problems generating a cert for my subdomain.
I have downloaded to hookscript, added all information to the auth file and updated the commandline for my subdomain, but when I run the command, it get stuck at
```
Are you OK with your IP being logged?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: y
```
After 12 minutes I cancelled the command with the following python error
According to the logfile, it got stuck here, before I cancelled:
```
2019-01-17 12:17:29,999:INFO:certbot.auth_handler:Performing the following challenges:
2019-01-17 12:17:30,001:INFO:certbot.auth_handler:dns-01 challenge for jj.dedyn.io
2019-01-17 12:29:41,132:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
[…]
```
[Here](https://pastebin.com/8G7mqAVz) is the full log file (without any tokens)

Any idea what could be the problem?

**Comment by peterthomassen** [comment]
In any case, the hook script produces text output: It will either say that it is going to set the ACME DNS challenge, that the configuration fiel `.dedynauth` is missing or invalid, or that the `curl` tool is not installed.

Your debug output contains no such output from the hook script, which implies that the script was not even called. The problem therefore happens somewhere earlier in the certbot process, and you'd need to debug that.

Are you using the most up to date certbot version?

Otherwise, it will probably be best to contact the Let's Encrypt / cerbot support channels (forum etc.).
